In [1]:
# %load ../preface.py
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns; sns.set()

# setup matplotlib
mpl.rcParams['font.family']='monospace'
mpl.rcParams['font.monospace']='Fira Code'
mpl.rcParams['font.size']=14.0
mpl.rcParams['figure.figsize']=[8,6]


In [41]:

import matplotlib as mpl
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

#fig = plt.figure()
#ax = fig.gca(projection='3d')

# # Make data.
# X = np.arange(-5, 5, 0.25)
# Y = np.arange(-5, 5, 0.25)
wv0 = np.arange(-5,5,1)
wv1 = np.arange(1,6,1)
X, Y = np.meshgrid(wv0, wv1)
# R = np.sqrt(X**2 + Y**2)
# nrows, ncols = X.shape
# #Z = np.sin(R)
# ax.plot_surface(X,Y,Z, cmap=cm.coolwarm, linewidth=0, antialiased=True)

In [44]:
np.empty((2,3))
        

array([[ 0.06824331,  0.07183185, -0.03412165],
       [ 0.05516321, -0.9591853 , -1.00962364]])

In [37]:
Y

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [38]:
for i in X:
    print(i)

[-5 -4 -3 -2 -1  0  1  2  3  4]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[-5 -4 -3 -2 -1  0  1  2  3  4]


In [4]:
# Loading data set
X, y = np.loadtxt('../datasets/cricket_chirps_versus_temperature.txt', delimiter=',', unpack=True)

data = np.genfromtxt('../datasets/cricket_chirps_versus_temperature.txt', delimiter=',')

def normalEquation(X, y):
    m = int(np.size(data[:, 1]))

    # This is the feature / parameter (2x2) vector that will
    # contain my minimized values
    theta = []

    # I create a bias_vector to add to my newly created X vector
    bias_vector = np.ones((m, 1))

    # I need to reshape my original X(m,) vector so that I can
    # manipulate it with my bias_vector; they need to share the same
    # dimensions.
    X = np.reshape(X, (m, 1))

    # I combine these two vectors together to get a (m, 2) matrix
    X = np.append(bias_vector, X, axis=1)

    # Normal Equation:
    # theta = inv(X^T * X) * X^T * y

    # For convenience I create a new, tranposed X matrix
    X_transpose = np.transpose(X)

    # Calculating theta
    theta = np.linalg.inv(X_transpose.dot(X))
    theta = theta.dot(X_transpose)
    theta = theta.dot(y)

    return theta

p = normalEquation(y, X)

print(p)

[24.96601443  3.30576144]


In [7]:
data[0]

array([88.6, 20. ])

In [8]:
X[0]

88.6