In [3]:
##tensorflow >2.0
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
print(tf.__version__)

2.9.1


In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
### Vocabulary size
voc_size=10000

### One-hot representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[3713, 5984, 6558, 186], [3713, 5984, 6558, 6037], [3713, 5847, 6558, 8143], [8715, 7424, 485, 4119, 6783], [8715, 7424, 485, 4119, 7239], [2940, 3713, 1820, 6558, 8044], [2395, 5123, 8840, 4119]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3713 5984 6558  186]
 [   0    0    0    0 3713 5984 6558 6037]
 [   0    0    0    0 3713 5847 6558 8143]
 [   0    0    0 8715 7424  485 4119 6783]
 [   0    0    0 8715 7424  485 4119 7239]
 [   0    0    0 2940 3713 1820 6558 8044]
 [   0    0    0    0 2395 5123 8840 4119]]


In [11]:
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

2022-09-23 10:57:49.922776: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 47ms/step
[[[-0.02811347  0.01694821 -0.00033017 -0.01611328 -0.03213336
    0.00396905 -0.03141411 -0.00919157  0.00920482 -0.02782282]
  [-0.02811347  0.01694821 -0.00033017 -0.01611328 -0.03213336
    0.00396905 -0.03141411 -0.00919157  0.00920482 -0.02782282]
  [-0.02811347  0.01694821 -0.00033017 -0.01611328 -0.03213336
    0.00396905 -0.03141411 -0.00919157  0.00920482 -0.02782282]
  [-0.02811347  0.01694821 -0.00033017 -0.01611328 -0.03213336
    0.00396905 -0.03141411 -0.00919157  0.00920482 -0.02782282]
  [ 0.02668175  0.00652166 -0.00964493  0.00401702  0.01769287
   -0.02338666  0.00290173 -0.00069126  0.04117571  0.01707126]
  [ 0.04017789  0.03212377 -0.04378221  0.03641244  0.01130226
    0.04440333 -0.02873696  0.02935351 -0.02060276 -0.01920364]
  [-0.02473721  0.00644792 -0.01440989  0.01751182 -0.0274722
   -0.0226087   0.04761959  0.03243629  0.03587157  0.049262  ]
  [-0.0102176  -0.0115964   0.00122629 -0.01737977  0.044725